blueprint:
  name: Scene Toggle
  description: This script toggles through scenes of a certain area based on its last activated timestamp.
  source_url: https://github.com/panhans/homeassistant/blob/main/blueprints/script/scene_toggle.yaml
  domain: script

  input:    
    area:
      name: Name of area
      description: Name of the area where you want to toggle scenes
      default: ''
      selector:
        area:
        
    included_scenes:
      name: Included Scenes
      description: Additional scenes to be included
      default: []
      selector:
        entity:
          domain: scene
          multiple: true
          
    excluded_scenes:
      name: Excluded Scenes
      description: Scenes to be excluded
      default: []
      selector:
        entity:
          domain: scene
          multiple: true
    
    transition:
      name: Transition time
      description: Transition time when switching between scenes
      default: 100
      selector:
        number:
          min: 0
          max: 10000
          unit_of_measurement: ms

mode: queued

variables:
  area: !input 'area'
  included_scenes: !input 'included_scenes'
  excluded_scenes: !input 'excluded_scenes'

sequence:
  - service: scene.turn_on
    data_template:
      transition: !input transition
      entity_id: >
        {%- set t = namespace(time = 0) %}
        {%- set s = namespace(scene = '') %}
        
        {%- for scene in states.scene if ((area_id(scene.entity_id) == area or scene.entity_id in included_scenes) and scene.entity_id not in excluded_scenes) %}
            {%- if (states[scene.entity_id].state == 'unknown' or (as_timestamp(states[scene.entity_id].state) < t.time) or t.time == 0) %}
              {%- set s.scene = scene.entity_id %}
              
              {% if (states[scene.entity_id].state == 'unknown') %}
                {%- set t.time = as_timestamp(now()) %}
              {%- else %}
                {%- set t.time = as_timestamp(states[scene.entity_id].state) %}
              {%- endif %}
            {%- endif %}  
        {%- endfor %}
        
        {{ s.scene }}
