blueprint:
  name: Scene Toggle
  description: This script toggles through scenes of a certain area based on its last activated timestamp.
  source_url: https://github.com/panhans/homeassistant/blob/main/blueprints/script/scene_toggle.yaml
  domain: script

  input:    
    area:
      name: Name of area
      description: Name of the area where you want to toggle scenes
      default: ''
      selector:
        area:
        
    included_scenes:
      name: Included Scenes
      description: Additional scenes to be included
      default: []
      selector:
        entity:
          domain: scene
          multiple: true
          
    excluded_scenes:
      name: Excluded Scenes
      description: Scenes to be excluded
      default: []
      selector:
        entity:
          domain: scene
          multiple: true
    
    transition:
      name: Transition time
      description: Transition time when switching between scenes
      default: 1
      selector:
        number:
          min: 0
          max: 10
          step: 0.1
          unit_of_measurement: s

mode: queued

variables:
  area: !input 'area'
  included_scenes: !input 'included_scenes'
  excluded_scenes: !input 'excluded_scenes'

sequence:
  - service: scene.turn_on
    data_template:
      transition: !input transition
      entity_id: >
        {% set area_scenes = states.scene | selectattr('entity_id', 'in', area_entities(area)) | map(attribute='entity_id') | list %}
        {% set all_scenes = (area_scenes | reject('in', excluded_scenes) | list) + included_scenes %}
        
        {%- set s = namespace(scene = '') %}
        {% set unknown_scenes = expand(all_scenes) | selectattr('state', 'eq', 'unknown') | map(attribute='entity_id') | list %}
        
        {% if unknown_scenes | count > 0 %}
        
          {%- set s.scene = unknown_scenes[0] %}
        
          {% else %}
            {% for scene in all_scenes %}
              {% if s.scene == '' %}
                {% set s.scene = scene %}
              {% endif %}
              {% if as_timestamp(states[scene].state) <  as_timestamp(states[s.scene].state) %}
                {% set s.scene = scene %}
              {% endif %}
            {% endfor %}
        
        {% endif %}
        
        {{ s.scene }}
